function [a1_g,a2_g,a3_g,a4_g,a5_g,a6_g,a7_g,a8_g] = initial_A(pose_trj,attach_e)

pose_ee = pose_trj(:,1);
x_step = pose_ee(1);
y_step = pose_ee(2);
z_step = pose_ee(3);
ax_step = pose_ee(4);
ay_step = pose_ee(5);
az_step = pose_ee(6);
a1_e = attach_e(:,1); a2_e = attach_e(:,2); a3_e = attach_e(:,3); a4_e = attach_e(:,4);
a5_e = attach_e(:,5); a6_e = attach_e(:,6); a7_e = attach_e(:,7); a8_e = attach_e(:,8);

% Calculate homogeneous transformation matrix
Tr_matrix = [1, 0, 0, x_step;...
    0, 1, 0, y_step;...
    0, 0, 1, z_step;...
    0, 0, 0,       1] * ...
    [cos(az_step), -sin(az_step), 0, 0;...
    sin(az_step),  cos(az_step), 0, 0;...
    0,             0, 1, 0;...
    0,             0, 0, 1] * ...
    [ cos(ay_step), 0, sin(ay_step), 0;...
    0, 1,            0, 0;...
    -sin(ay_step), 0, cos(ay_step), 0;...
    0, 0,            0, 1] * ...
    [1,            0,             0, 0;...
    0, cos(ax_step), -sin(ax_step), 0;...
    0, sin(ax_step),  cos(ax_step), 0;...
    0,            0,             0, 1];

% Coordinates of attachment points converted to the global frame
a1_g = Tr_matrix * a1_e;
a2_g = Tr_matrix * a2_e;
a3_g = Tr_matrix * a3_e;
a4_g = Tr_matrix * a4_e;
a5_g = Tr_matrix * a5_e;
a6_g = Tr_matrix * a6_e;
a7_g = Tr_matrix * a7_e;
a8_g = Tr_matrix * a8_e;
end